#-------------------------------
# General Site Settings

menu:
- {name: 'Pages', url: 'pages/posts'}
- {name: 'Schedule', url: 'pages/schedule'}
- {name: 'Syllabus', url: 'pages/syllabus'}
- {name: 'Contact', url: 'pages/contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Class website for Purchase College CS1, Fall 2022'

#-------------------------------
# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'namegoeshere'

#-------------------------------
# About Section

about: >
  # CS1

  This is the class website for CS1, fall 2022 at Purchase College, taught by Lee Tusman.

  You can find our course Moodle page [here](https://moodle.purchase.edu/moodle2/login/index.php). Our class Discord server is linked from Moodle as well.

  Our class meets in person or on Zoom Mondays at 2:30pm.

contact: >
  # Contact

  You may contact Lee through [email](mailto:lee.tusman@purchase.edu) if you have any questions or would like to bring up any issues.

#-------------------------------
# Work Section

projects:
# To list project pages, uncomment the following lines and add these files!
#- {name: 'Project One', folder: 'proj-1', file: 'projects/proj-1.html'}
#- {name: 'Project Two', folder: 'proj-2', file: 'projects/proj-2.html'}
#- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}

#-------------------------------
# Contact Section

social:
#- {icon: 'twitter', link: '#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
